### ISSUE TITLE
Lowercase z is not included 

### ISSUE THREAD

**Issue by tfantina** [Dallaire/ruby_building_blocks#1]
Hey, I found this via The Odin Project, I just finished working through this exercise as well.  I really like your code, it seems concise and clean.  One thing I noticed on line 5: `if ("A"..."z").include? (i)` that will exclude lowercase z, to include lowercase z it should be `if ("A".."z").include? (i)`.  (... includes everything UP to a specified point in a range whereas .. includes everything INCLUDING that point).

**Comment by Dallaire** [comment]
Thank you for pointing this out. I actually committed the fix as part of the testing section before I saw your issue. 
Wish I had seen it earlier as I spent a while thinking it was an issue with my asci numbers before I noticed the (...) mistake.
